spring.application.name=ProjectsCompetitionPlatform
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.platform=h2
spring.h2.console.enabled=true
spring.profiles.active=dev

spring.cloudinary.cloudName=
spring.cloudinary.apiKey=
spring.cloudinary.apiSecret=
spring.cloudinary.folder=

jwt.expiration.duration.access=10m
jwt.expiration.duration.refresh=30d

image.rest.controller.enabled=true
competition.minProjects=3
competition.maxProjects=5

user.password.min-length=8

oauth2.state=sign_in
oauth2.google.url.apis=https://oauth2.googleapis.com
oauth2.google.url.authPage=https://accounts.google.com/o/oauth2/v2/auth
oauth2.google.client.id=
oauth2.google.client.secret=
oauth2.google.scope=

payment.enable=true

log.file.path=logs/all_logs.log